version: '3.1'
services:
  php:
     build:
          args:
              user: www-data
              uid: 1000
          context: ./docker/php-8.0/
     container_name: php-fpm2
     restart: unless-stopped
     ports:
        - 84:80

     environment:
          WWWUSER: '${WWWUSER}'
     volumes:
          - '.:/var/www/html'
     networks:
         - app
     depends_on:
         - mysql

  mysql:
        image: mysql:latest
        container_name: mysqlDb
        restart: unless-stopped
        tty: true
        ports:
            - "3309:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'aspasia'
            DB_PASSWORD: 'root'
        volumes:
          - ./docker/mysql:/var/lib/mysql

        networks:
            - app
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
          retries: 3
          timeout: 5s

networks:
    app:
        driver: bridge
volumes:
    appmysql:
        driver: local

